name: Integration Tests

on:

  push:
    branches: [main]

  pull_request:

permissions:

  contents: read

jobs:

  tests:
    name: Integration Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '5.6'
          - '7.4'
          - '8.2'
        wordpress:
          - 'latest'
        include:
          - php: '5.6'
            wordpress: '5.0'
          - php: '7.4'
            wordpress: '5.3'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Validate composer.json
        run: composer validate --strict

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Override WordPress version
        if: ${{ matrix.wordpress != 'latest' }}
        run: |
          composer require roots/wordpress:^${{ matrix.wordpress }} --dev --no-update
          composer require wp-phpunit/wp-phpunit:^${{ matrix.wordpress }} --dev --no-update
          composer require phpunit/phpunit:^5.6 --dev --no-update

      - name: Install Composer dependencies
        run: composer update --ansi --no-interaction --no-progress --prefer-dist

      - name: Run integration tests
        run: composer run test:integration
